In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

b= np.array ([4,5,6])
print(a+b)

[5 7 9]


In [4]:
print(a*b)

[ 4 10 18]


In [5]:
print(a/b)

[0.25 0.4  0.5 ]


In [6]:
print(a-b)

[-3 -3 -3]


In [7]:
print(a**3) # exponent

[ 1  8 27]


In [8]:
print (np.sqrt(a)) # to find the sq root

[1.         1.41421356 1.73205081]


In [9]:
print (np.power(a,5)) # for n exponent

[  1  32 243]


In [18]:
arr= np.array([10,20,20,30,40,50])

In [15]:
print(np.mean(arr)) # to find the average

28.333333333333332


In [16]:
print (np.median(arr))

25.0


In [19]:
print(np.max(arr)) # highest value

50


In [20]:
print(np.min(arr)) # lowest value

10


In [21]:
print (np.sum(arr)) # total value

170


In [22]:
print(np.std(arr)) # standard deviation

13.43709624716425


In [23]:
print(np.var(arr)) # variance

180.55555555555557


In [26]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2],[3,4]])


In [40]:
arr= np.array([[1,2,3],
               [4,5,6]])
print (arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.arange(1,11) # array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.random.rand(5)

array([0.40863752, 0.3003412 , 0.0549046 , 0.61880775, 0.19838993])

In [46]:
np.random.randint(1,100,10) # give random integers

array([47,  1, 10, 85, 97, 36, 81, 14, 61, 71])

In [41]:
arr= np.array([5,2,9,1])
print (np.sort(arr))

[1 2 5 9]


In [42]:
arr= np.array([1,2,2,3,3,4])
print(np.unique(arr))

[1 2 3 4]


In [43]:
a= np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate)((a,b))

<built-in function concatenate>


In [44]:
arr= np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [45]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]
